name: Build, tag, and publish a release

on:
  push:
    branches:
      - main
      - public

jobs:
  tag:
    name: Create tag for new version
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_new_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: create_new_tag

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: tag
    if: needs.tag.outputs.tag_name
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.tag_name }}
          release_name: ${{ needs.tag.outputs.tag_name }}
          draft: false
          prerelease: false